on:
  push:
    branches: [ cmake-and-ci ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run build and test script (shell)
        run: ls -pal #./.github/scripts/build-and-test.sh
