on:
  push:
    branches: [ cmake-and-ci main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run build and test script (shell)
        run: ./.github/scripts/build-and-test.sh
